// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: imss.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StoreStatus_Code int32

const (
	StoreStatus_Ok  StoreStatus_Code = 0
	StoreStatus_Bad StoreStatus_Code = 1
)

// Enum value maps for StoreStatus_Code.
var (
	StoreStatus_Code_name = map[int32]string{
		0: "Ok",
		1: "Bad",
	}
	StoreStatus_Code_value = map[string]int32{
		"Ok":  0,
		"Bad": 1,
	}
)

func (x StoreStatus_Code) Enum() *StoreStatus_Code {
	p := new(StoreStatus_Code)
	*p = x
	return p
}

func (x StoreStatus_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreStatus_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_imss_proto_enumTypes[0].Descriptor()
}

func (StoreStatus_Code) Type() protoreflect.EnumType {
	return &file_imss_proto_enumTypes[0]
}

func (x StoreStatus_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreStatus_Code.Descriptor instead.
func (StoreStatus_Code) EnumDescriptor() ([]byte, []int) {
	return file_imss_proto_rawDescGZIP(), []int{3, 0}
}

type Respone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Respone) Reset() {
	*x = Respone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respone) ProtoMessage() {}

func (x *Respone) ProtoReflect() protoreflect.Message {
	mi := &file_imss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respone.ProtoReflect.Descriptor instead.
func (*Respone) Descriptor() ([]byte, []int) {
	return file_imss_proto_rawDescGZIP(), []int{0}
}

func (x *Respone) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_imss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_imss_proto_rawDescGZIP(), []int{1}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *StoreReq) Reset() {
	*x = StoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReq) ProtoMessage() {}

func (x *StoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_imss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReq.ProtoReflect.Descriptor instead.
func (*StoreReq) Descriptor() ([]byte, []int) {
	return file_imss_proto_rawDescGZIP(), []int{2}
}

func (x *StoreReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoreStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status StoreStatus_Code `protobuf:"varint,1,opt,name=Status,proto3,enum=imss_v1.StoreStatus_Code" json:"Status,omitempty"`
}

func (x *StoreStatus) Reset() {
	*x = StoreStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStatus) ProtoMessage() {}

func (x *StoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_imss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStatus.ProtoReflect.Descriptor instead.
func (*StoreStatus) Descriptor() ([]byte, []int) {
	return file_imss_proto_rawDescGZIP(), []int{3}
}

func (x *StoreStatus) GetStatus() StoreStatus_Code {
	if x != nil {
		return x.Status
	}
	return StoreStatus_Ok
}

var File_imss_proto protoreflect.FileDescriptor

var file_imss_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x6d, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x69, 0x6d,
	0x73, 0x73, 0x5f, 0x76, 0x31, 0x22, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x22, 0x32, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x69, 0x6d, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x17, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x61, 0x64, 0x10,
	0x01, 0x32, 0x69, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x69, 0x6d, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x69, 0x6d, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x11, 0x2e, 0x69, 0x6d, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x69, 0x6d, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6c, 0x2d, 0x61,
	0x73, 0x2f, 0x69, 0x6d, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imss_proto_rawDescOnce sync.Once
	file_imss_proto_rawDescData = file_imss_proto_rawDesc
)

func file_imss_proto_rawDescGZIP() []byte {
	file_imss_proto_rawDescOnce.Do(func() {
		file_imss_proto_rawDescData = protoimpl.X.CompressGZIP(file_imss_proto_rawDescData)
	})
	return file_imss_proto_rawDescData
}

var file_imss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_imss_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_imss_proto_goTypes = []interface{}{
	(StoreStatus_Code)(0), // 0: imss_v1.StoreStatus.Code
	(*Respone)(nil),       // 1: imss_v1.Respone
	(*GetReq)(nil),        // 2: imss_v1.GetReq
	(*StoreReq)(nil),      // 3: imss_v1.StoreReq
	(*StoreStatus)(nil),   // 4: imss_v1.StoreStatus
}
var file_imss_proto_depIdxs = []int32{
	0, // 0: imss_v1.StoreStatus.Status:type_name -> imss_v1.StoreStatus.Code
	2, // 1: imss_v1.Storage.Get:input_type -> imss_v1.GetReq
	3, // 2: imss_v1.Storage.Store:input_type -> imss_v1.StoreReq
	1, // 3: imss_v1.Storage.Get:output_type -> imss_v1.Respone
	4, // 4: imss_v1.Storage.Store:output_type -> imss_v1.StoreStatus
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_imss_proto_init() }
func file_imss_proto_init() {
	if File_imss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imss_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imss_proto_goTypes,
		DependencyIndexes: file_imss_proto_depIdxs,
		EnumInfos:         file_imss_proto_enumTypes,
		MessageInfos:      file_imss_proto_msgTypes,
	}.Build()
	File_imss_proto = out.File
	file_imss_proto_rawDesc = nil
	file_imss_proto_goTypes = nil
	file_imss_proto_depIdxs = nil
}
